### PR TITLE
Styles

### PR DESCRIPTION
**Pull request by vittopan**
Here's all the changes I have made over the past few days...

### CODE REVIEW

**Comment by tomve1tch** [comment]
Styles look phenomenal. Aligns perfectly with Vito's concept drawings. Will need to resolve conflicts when merging :)

**Comment by saundlj** [comment]
Love the style! fantastic job Vito, this is looking really good. I have a few suggestion you can try implement before implementing:
- Make the nav bar stand out more (bigger and more clear font)
- Use javascript for toggling the job map? (this may need some more research but I feel its definitely something JS can handle)
-  Jazz up the about page to be a bit visually appealing but the content is _really_ good!

Set up a really good platform and nice to see the web app coming together!

**Comment by saundlj** [comment]
Also lets try resolve these merge conflicts in our meeting tomorrow. Its best if we both work through the code so nothing important gets deleted!

**Comment by mjb44552** [comment]
Style looks great Vito, happy with how it has been implemented.

**Pull request merged**
